companies = [
    {
        "name": "NVIDIA",
        "platform": "workday",
        "url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    },
    {
        "name": "Apple",
        "platform": "apple",
        "url": "https://jobs.apple.com/en-il/search?location=israel-ISR",
    },
    {
        "name": "Broadcom",
        "platform": "workday",
        "url": "https://www.broadcom.com/company/careers",
    },
    {
        "name": "Intel",
        "platform": "workday",
        "url": "https://intel.wd1.myworkdayjobs.com/en-US/External?locations=1e4a4eb3adf1013563ba9174bf817fcd&locations=1e4a4eb3adf101aaeda8a474bf818ecd&locations=1e4a4eb3adf101f41cd29774bf8184cd",
    },
    {
        "name": "Microsoft",
        "platform": "microsoft",
        "url": "https://www.microsoftrnd.co.il/jobs",
    },
    {
        "name": "Google",
        "platform": "google",
        "url": "https://www.google.com/about/careers/applications/jobs/results/?location=Israel",
    },
    {
        "name": "Amazon",
        "platform": "amazon",
        "url": "https://www.amazon.jobs/en/search?country%5B%5D=ISR",
    },
    {
        "name": "Qualcomm",
        "platform": "eightfold",
        "url": "https://careers.qualcomm.com/",
        "domain": "qualcomm.com",
        "search_location": "Israel",
    },
    {
        "name": "Marvell",
        "platform": "workday",
        "url": "https://www.marvell.com/company/careers.html",
    },
    {
        "name": "Cadence",
        "platform": "dejobs",
        "url": "https://cadence.dejobs.org/locations/isr/jobs/",
    },
    {
        "name": "Synopsys",
        "platform": "synopsys",
        "url": "https://careers.synopsys.com/search-jobs/Israel",
    },
    {
        "name": "Mobileye",
        "platform": "mobileye",
        "url": "https://www.mobileye.com/careers/",
    },
    {
        "name": "Nuvoton",
        "platform": "custom",
        "url": "https://nuvoton.co.il/careers/",
    },
    {
        "name": "Tower Semiconductor",
        "platform": "tower",
        "url": "https://careers.towersemi.com/career-opportunities/engineering/",
    },
    {
        "name": "Applied Materials",
        "platform": "custom",
        "url": "https://jobs.appliedmaterials.com/location/israel-jobs/95/294640/2",
    },
    {
        "name": "KLA",
        "platform": "workday",
        "url": "https://kla.wd1.myworkdayjobs.com/Israel",
    },
    {
        "name": "Nova",
        "platform": "comeet",
        "url": "https://www.comeet.com/jobs/nova/A5.007",
        "country": "IL",
        "allowed_departments": [
            "Engineering",
            "Manufacture Engineering",
            "Production",
            "Research & Development",
        ],
    },
    {
        "name": "SolarEdge",
        "platform": "custom",
        "url": "https://www.comeet.com/jobs/solaredge/71.00A",
    },
    {
        "name": "Rafael",
        "platform": "getro",
        "url": "https://jobs.lhh.co.il/companies/rafael-advanced-defense-systems",
        "network_id": "1200",
        "organization_id": 23055,
    },
    {
        "name": "Israel Aerospace Industries",
        "platform": "static_json",
        "url": "https://jobs.iai.co.il/jobs/",
        "feed_url": "https://jobs.iai.co.il/wp-content/themes/tyco-wp/assets/json/jobs.json",
        "id_field": "id",
        "title_field": "tl",
        "location_fields": ["ct"],
        "text_fields": ["tl", "dc", "jc", "ct"],
        "allowed_field_values": {
            "jc": ["הנדסה ופיתוח", "הנדסאים/טכנאים", "סטודנטים"],
        },
        "url_template": "https://jobs.iai.co.il/job/{id}",
    },
    {
        "name": "Elbit",
        "platform": "static_json",
        "url": "https://elbitsystemscareer.com/",
        "feed_url": "https://elbitsystemscareer.com/cron/jobs.json",
        "id_field": "jobId",
        "title_field": "jobTitle",
        "location_fields": ["locationAddress"],
        "text_fields": [
            "jobTitle",
            "description",
            "requirements",
            "skills",
            "area",
            "employerName",
        ],
        "url_template": "https://elbitsystemscareer.com/job?jid={id}",
        "identity_url_template": "https://elbitsystemscareer.com/?page=search&jobId={id}",
        "default_location": "Israel",
        "allowed_field_values": {
            "categoryId": [1, 3, 4],
        },
    },
]
