keywords = [
    "Physical Design",
    "ASIC",
    "VLSI",
    "RTL",
    "FPGA",
    "Verification",
    "Design Verification",
    "UVM",
    "SystemVerilog",
    "Verilog",
    "Board Design",
    "Hardware",
    "HW",
    "Electrical Engineer",
    "System Integration",
    "Integration Engineer",
    "Firmware",
    "Embedded",
    "DSP",
    "PCB",
    "Signal Integrity",
    "Power Integrity",
    "DDR",
    "PCIe",
    "STA",
    "Timing",
    "Place and Route",
    "Floorplanning"
]

locations = [
    "Israel",
    "Tel Aviv",
    "Haifa",
    "Herzliya",
    "Jerusalem",
    "Yokneam",
    "Migdal Haemek",
    "Migdal-Haemek",
    "Ra'anana",
    "Rehovot",
    "Petah Tikva",
    "Petah-Tikva",
    "Netanya"
]
